
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 107
#define YY_END_OF_BUFFER 108
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[345] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  108,    8,
        2,    8,    8,    8,   10,   11,  107,    9,  107,   13,
       13,   17,   16,   15,   19,   18,   23,   22,   21,   27,
       28,  107,   25,   24,   31,   32,   31,   29,   38,   37,
       34,   38,   40,   39,   41,   40,   52,   52,   44,   46,

       52,   52,   52,   52,   55,   56,   59,   59,   54,   53,
       58,   58,   63,   62,   61,   65,   64,   69,   68,   67,
       73,   74,  107,   71,   70,   77,   78,   77,   75,   84,
       83,   80,   84,   86,   85,   87,   86,   98,   98,   90,
       92,   98,   98,   98,   98,  101,  102,  105,  105,  100,
       99,  104,  104,    0,    0,    0,    0,    0,    0,    0,
       20,   26,   30,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   66,   72,   76,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    4,    0,    0,    7,   12,

       14,   26,   30,    0,   36,    0,    0,   48,    0,    0,
       51,    0,   60,   57,   72,   76,    0,   82,    0,    0,
       94,    0,    0,   97,    0,  106,  103,    0,    0,    0,
        0,    0,    0,   39,    0,    0,    0,    0,    0,   60,
        0,   57,    0,    0,    0,   85,    0,    0,    0,    0,
        0,  106,    0,  103,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    1,    0,    0,    0,    0,   33,    0,    0,

       45,    0,    0,    0,   43,   42,    0,   79,    0,    0,
       91,    0,    0,    0,   89,   88,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    3,    5,
        6,    0,   35,    0,   47,   49,   50,    0,   81,    0,
       93,   95,   96,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    6,    7,
        8,    1,    1,    9,    1,    1,    1,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,    1,    1,
       12,    1,    1,   13,    1,    1,    1,   14,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   15,    1,
        1,    1,    1,   16,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   17,    1,   18,   19,

       20,   21,    1,    1,    1,    1,    1,    1,    1,   22,
        1,   23,    1,   24,   25,   26,   27,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[28] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[379] =
    {   0,
        0,    2,  482,  481,  480,  479,  475,  474,  473,  472,
        1,    8,  474,  473,   19,   21,   27,   38,   29,   40,
       48,   52,   57,   60,   63,   86,  472,  471,  467,  466,
      468,  467,  463,  462,   69,   71,  464,  463,   90,   97,
      109,  120,   99,  111,   78,  128,  123,  133,  136,  159,
      462,  461,  457,  456,  458,  457,  453,  452,  457,  486,
      452,  449,    3,  434,  486,  486,  486,  486,  447,  486,
      446,  486,  486,  486,  486,  486,  486,  486,    0,  486,
      486,  440,  486,  486,  486,  486,  439,  486,  486,  486,
      445,  442,  486,  486,  486,  443,  486,  142,  149,  442,

      439,   28,  424,  423,  486,  486,  486,  436,  486,  486,
      486,  435,  486,  486,  486,  486,  486,  486,  486,    0,
      486,  486,  429,  486,  486,  486,  486,  428,  486,  486,
      486,  434,  431,  486,  486,  486,  432,  486,  182,    0,
      431,  428,   92,  413,  412,  486,  486,  486,  425,  486,
      486,  486,  424,  413,  422,  409,  406,  404,  418,  417,
        0,    0,    0,  406,  415,  416,  155,  399,  402,  411,
      398,  395,  393,  387,  406,  405,    0,    0,    0,  394,
      403,  404,    0,  126,  387,  386,  389,  398,  385,  382,
      380,  374,  393,  392,  382,  392,  377,  368,  486,  486,

      486,    0,    0,  378,  388,  387,  375,  385,  370,  361,
      486,  359,   67,   82,    0,    0,  370,  380,  379,  367,
      377,  362,  353,  486,  351,   92,  144,  363,  360,  355,
      347,  359,  356,  486,  357,  354,  349,  341,  343,  486,
      164,  486,  166,  352,  349,  486,  350,  347,  342,  334,
      336,  486,  171,  486,  173,  344,  343,  334,  332,  340,
      339,  338,  337,  328,  326,  327,  333,  332,  331,  330,
      321,  319,  320,  170,  327,  314,  317,  177,  324,  179,
      323,  310,  313,  188,  183,  320,  186,  319,  305,  306,
      195,  192,  486,  310,  297,  175,  194,  486,  167,  197,

      486,  156,  131,  129,  486,  486,  199,  486,  115,  201,
      486,   91,   73,   50,  486,  486,  203,   66,   49,  205,
      207,   27,   11,  209,  211,    7,    5,  213,  486,  486,
      486,  215,  486,  217,  486,  486,  486,  219,  486,  221,
      486,  486,  486,  486,  232,  235,  238,  241,  244,  247,
      250,  253,  256,  259,  262,  265,  268,  271,  274,  277,
      280,  283,  286,  289,  292,  295,  298,  301,  304,  307,
      310,  313,  316,  318,  320,  323,  326,  329
    } ;

static yyconst flex_int16_t yy_def[379] =
    {   0,
      345,  345,  346,  346,  347,  347,  347,  347,  348,  348,
      349,  349,  350,  350,  351,  351,  352,  352,  353,  353,
      354,  354,  355,  355,  356,  356,  357,  357,  358,  358,
      359,  359,  360,  360,  361,  361,  362,  362,  363,  363,
      364,  364,  365,  365,  366,  366,  367,  367,  368,  368,
      369,  369,  370,  370,  371,  371,  372,  372,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  373,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  374,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  139,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      373,  375,  376,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  374,  377,  378,  344,
      344,  344,  139,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  375,  376,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  377,  378,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,    0,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344
    } ;

static yyconst flex_uint16_t yy_nxt[514] =
    {   0,
      344,  344,  344,   73,   61,   62,   61,   62,   74,   74,
       73,  343,   63,  342,   63,   74,   74,  337,   64,  156,
       64,   67,   78,   67,   78,   79,  157,   79,   81,   81,
       81,   86,   86,  336,   82,   83,   87,   88,   84,   81,
       81,   81,   86,   86,  171,   82,   83,   87,   88,   84,
       90,  172,   91,   92,   90,  331,   91,   92,   94,   95,
       96,   94,   95,   96,   98,   99,   98,  100,  101,  240,
      241,  114,  330,  114,  327,  102,  115,  115,  115,  115,
      131,  103,  132,  133,  242,  243,  104,   98,   99,   98,
      100,  101,   67,  119,  252,  253,  120,  326,  102,   67,

      119,  127,  127,  120,  103,  325,  128,  129,  189,  104,
      122,  122,  122,  127,  127,  190,  123,  124,  128,  129,
      125,  122,  122,  122,  135,  136,  137,  123,  124,  324,
      131,  125,  132,  133,  135,  136,  137,  139,  140,  139,
      141,  142,  189,  167,  167,  167,  254,  255,  143,  190,
      167,  167,  167,  323,  144,  322,  167,  167,  167,  145,
      139,  140,  139,  141,  142,  168,  240,  241,  242,  243,
      321,  143,  168,  252,  253,  254,  255,  144,  168,  292,
      293,  320,  145,  183,  183,  183,  297,  298,  300,  301,
      305,  306,  307,  308,  184,  310,  311,  315,  316,  319,

      185,  292,  293,  297,  298,  186,  300,  301,  307,  308,
      310,  311,  328,  329,  332,  333,  334,  335,  338,  339,
      340,  341,  328,  329,  332,  333,  334,  335,  338,  339,
      340,  341,   60,   60,   60,   65,   65,   65,   67,   67,
       67,   70,   70,   70,   72,   72,   72,   75,   75,   75,
       77,   77,   77,   80,   80,   80,   85,   85,   85,   89,
       89,   89,   93,   93,   93,   97,   97,   97,  105,  105,
      105,  107,  107,  107,  109,  109,  109,  111,  111,  111,
      113,  113,  113,  116,  116,  116,  118,  118,  118,  121,
      121,  121,  126,  126,  126,  130,  130,  130,  134,  134,

      134,  138,  138,  138,  146,  146,  146,  148,  148,  148,
      150,  150,  150,  152,  152,  152,  161,  161,  177,  177,
      202,  318,  202,  203,  317,  203,  215,  314,  215,  216,
      313,  216,  312,  309,  304,  303,  302,  299,  296,  295,
      294,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  251,  250,  249,
      248,  247,  246,  245,  244,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,

      224,  223,  222,  221,  220,  192,  191,  219,  218,  217,
      214,  213,  212,  211,  210,  209,  208,  207,  174,  206,
      205,  204,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  188,  187,  182,  181,  180,  179,  178,
      176,  175,  174,  173,  170,  169,  166,  165,  164,  163,
      162,  160,  159,  158,  155,  154,  344,  153,  153,  151,
      151,  149,  149,  147,  147,  117,  117,  112,  112,  110,
      110,  108,  108,  106,  106,   76,   76,   71,   71,   69,
       69,   68,   68,   66,   66,   59,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344
    } ;

static yyconst flex_int16_t yy_chk[514] =
    {   0,
        0,    0,    0,   11,    1,    1,    2,    2,   11,   11,
       12,  327,    1,  326,    2,   12,   12,  323,    1,   63,
        2,   15,   15,   16,   16,   15,   63,   16,   17,   17,
       17,   19,   19,  322,   17,   17,   19,   19,   17,   18,
       18,   18,   20,   20,  102,   18,   18,   20,   20,   18,
       21,  102,   21,   21,   22,  319,   22,   22,   23,   23,
       23,   24,   24,   24,   25,   25,   25,   25,   25,  213,
      213,   35,  318,   36,  314,   25,   35,   35,   36,   36,
       45,   25,   45,   45,  214,  214,   25,   26,   26,   26,
       26,   26,   39,   39,  226,  226,   39,  313,   26,   40,

       40,   43,   43,   40,   26,  312,   43,   43,  143,   26,
       41,   41,   41,   44,   44,  143,   41,   41,   44,   44,
       41,   42,   42,   42,   47,   47,   47,   42,   42,  309,
       46,   42,   46,   46,   48,   48,   48,   49,   49,   49,
       49,   49,  184,   98,   98,   98,  227,  227,   49,  184,
       99,   99,   99,  304,   49,  303,  167,  167,  167,   49,
       50,   50,   50,   50,   50,   98,  241,  241,  243,  243,
      302,   50,   99,  253,  253,  255,  255,   50,  167,  274,
      274,  299,   50,  139,  139,  139,  278,  278,  280,  280,
      284,  284,  285,  285,  139,  287,  287,  291,  291,  296,

      139,  292,  292,  297,  297,  139,  300,  300,  307,  307,
      310,  310,  317,  317,  320,  320,  321,  321,  324,  324,
      325,  325,  328,  328,  332,  332,  334,  334,  338,  338,
      340,  340,  345,  345,  345,  346,  346,  346,  347,  347,
      347,  348,  348,  348,  349,  349,  349,  350,  350,  350,
      351,  351,  351,  352,  352,  352,  353,  353,  353,  354,
      354,  354,  355,  355,  355,  356,  356,  356,  357,  357,
      357,  358,  358,  358,  359,  359,  359,  360,  360,  360,
      361,  361,  361,  362,  362,  362,  363,  363,  363,  364,
      364,  364,  365,  365,  365,  366,  366,  366,  367,  367,

      367,  368,  368,  368,  369,  369,  369,  370,  370,  370,
      371,  371,  371,  372,  372,  372,  373,  373,  374,  374,
      375,  295,  375,  376,  294,  376,  377,  290,  377,  378,
      289,  378,  288,  286,  283,  282,  281,  279,  277,  276,
      275,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  251,
      250,  249,  248,  247,  245,  244,  239,  238,  237,  236,
      235,  233,  232,  231,  230,  229,  228,  225,  223,  222,
      221,  220,  219,  218,  217,  212,  210,  209,  208,  207,
      206,  205,  204,  198,  197,  196,  195,  194,  193,  192,

      191,  190,  189,  188,  187,  186,  185,  182,  181,  180,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  166,
      165,  164,  160,  159,  158,  157,  156,  155,  154,  153,
      149,  145,  144,  142,  141,  137,  133,  132,  128,  123,
      112,  108,  104,  103,  101,  100,   96,   92,   91,   87,
       82,   71,   69,   64,   62,   61,   59,   58,   57,   56,
       55,   54,   53,   52,   51,   38,   37,   34,   33,   32,
       31,   30,   29,   28,   27,   14,   13,   10,    9,    8,
        7,    6,    5,    4,    3,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tema.l"
/* MAFTEI Stefan - Radu, grupa 336CC */
#line 3 "tema.l"
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	#define MAX_BUFF 100

	// details for functions' parameters
	typedef struct param {
		int size_of_name;
		int size_of_defaultValue;
		char* name;
		int hasDefaultValue;
		char* defaultValue;
	} TParam;

	// python functions details
	typedef struct functionPy{
		int size_of_name;
		char* name;
		int nrParamsAccept;
		int isDecoratorReturn;
		int nrReturns;
		int nrParams;
		TParam* params;
		int nrCodeLines;
		int nrTODOs;
	} TFunctionPy;

	int alreadyAllocated = 0; // a function has been allocated because of a decorator
	int nr_functions = 0, nr_functions_aux; // nr of functions at the moment
	TFunctionPy* functions; // current functions

	// print details about the function till parameters' default values
	void printFunctionPart1()
	{
		int i;
		if (nr_functions > 1)
		{
			printf("\ninner ");
		}

		if (functions[nr_functions - 1].nrParams > 0)
		{
			printf("function %s(", functions[nr_functions - 1].name);
		}
		else
		{
			printf("function %s()\n", functions[nr_functions - 1].name);
		}

		for (i = 0; i < functions[nr_functions - 1].nrParams - 1; i++)
		{
			printf("%s, ", functions[nr_functions - 1].params[i].name);
		}
		if (functions[nr_functions - 1].nrParams > 0)
		{
			printf("%s)\n", functions[nr_functions - 1].params[i].name);
		}

		for (i = 0; i < functions[nr_functions - 1].nrParams; i++)
		{
			if (functions[nr_functions - 1].params[i].hasDefaultValue == 1)
			{
				printf("parameter %s has default value %s\n", functions[nr_functions - 1].params[i].name, functions[nr_functions - 1].params[i].defaultValue);
			}
		}	
	}

	// print details about the function from number of code lines till the end
	void printFunctionPart2()
	{
		int i;

		printf("has %d lines of code\n", functions[nr_functions - 1].nrCodeLines);

		if (functions[nr_functions - 1].nrReturns > 0)
		{
			printf("has returns\n");
		}

		if (functions[nr_functions - 1].nrTODOs > 0)
		{
			printf("function incomplete: %d TODOs remaining\n", functions[nr_functions - 1].nrTODOs);
		}

		if (functions[nr_functions - 1].nrParamsAccept != -1 && functions[nr_functions - 1].nrParamsAccept != functions[nr_functions - 1].nrParams)
		{
			printf("decorator inconsistency: wrong parameter number\n");
		}

		if (functions[nr_functions - 1].isDecoratorReturn == 1 && functions[nr_functions - 1].nrReturns == 0)
		{
			printf("decorator inconsistency: no return found\n");
		}

		printf("\n");
	}

	// free allocated space
	void freeFunction()
	{
		int i;
		for (i = 0; i < functions[nr_functions - 1].nrParams; i++)
		{
			free(functions[nr_functions - 1].params[i].name);
			free(functions[nr_functions - 1].params[i].defaultValue);
		}
		free(functions[nr_functions - 1].params);
		free(functions[nr_functions - 1].name);

		if (nr_functions == 1)
		{
			free(functions);
		}
	}






#line 803 "lex.yy.c"

#define INITIAL 0
#define commentSharp 1
#define commentSharpTask 2
#define commentQuoteTask 3
#define commentQuote 4
#define decoratorAccepts 5
#define decoratorReturns 6
#define mainFunction 7
#define mainFunctionParams 8
#define mainFunctionParamsDefaultValues 9
#define mainFunctionLines 10
#define mainFunctionLinesBegin 11
#define mainFunctionReturnLines 12
#define mainFunctionCommentSharp 13
#define mainFunctionCommentQuote 14
#define mainFunctionCommentSharpTODO 15
#define mainFunctionCommentQuoteTODO 16
#define decoratorAcceptsInner 17
#define decoratorReturnsInner 18
#define innerFunction 19
#define innerFunctionParams 20
#define innerFunctionParamsDefaultValues 21
#define innerFunctionLines 22
#define innerFunctionLinesBegin 23
#define innerFunctionReturnLines 24
#define innerFunctionCommentSharp 25
#define innerFunctionCommentQuote 26
#define innerFunctionCommentSharpTODO 27
#define innerFunctionCommentQuoteTODO 28

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 130 "tema.l"

#line 1051 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 345 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 486 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 131 "tema.l"
{ BEGIN(commentSharpTask);
										printf("found task:"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 133 "tema.l"
{ BEGIN(commentSharp); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 134 "tema.l"
{ BEGIN(commentQuoteTask);
											printf("found task:"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 136 "tema.l"
{ BEGIN(commentQuote); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 137 "tema.l"
{ // accepts decorator for outer function
					   BEGIN(decoratorAccepts);
					   // allocate the function that comes next
					   nr_functions++;
					   functions = (TFunctionPy*) malloc(sizeof(TFunctionPy));
					   functions->nrParamsAccept = 0;
					   functions->nrReturns = 0;
					   functions->nrParams = 0;
					   functions->isDecoratorReturn = 0;
					   alreadyAllocated = 1; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 147 "tema.l"
{ // returns decorator for outer function
					   BEGIN(decoratorReturns);
					   if (alreadyAllocated == 1)
					   {
					   		functions->isDecoratorReturn = 1;
					   }
					   else
					   {
							nr_functions++;
							functions = (TFunctionPy*) malloc(sizeof(TFunctionPy));
							functions->nrParamsAccept = -1;
							functions->isDecoratorReturn = 1;
							functions->nrParams = 0;
							alreadyAllocated = 1;
					   }; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 162 "tema.l"
{ // outer function found
				 BEGIN(mainFunction);
				 if (alreadyAllocated == 1)
			     {
			   		alreadyAllocated = 0;
			   	 }
			     else
			     {
					nr_functions++;
					functions = (TFunctionPy*) malloc(sizeof(TFunctionPy));
					functions->nrParamsAccept = -1;
					functions->nrParams = 0;
					alreadyAllocated = 0;
			     };
			     functions->size_of_name = 0;
			     functions->name = (char*) calloc(MAX_BUFF, sizeof(char)); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 178 "tema.l"
;
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 180 "tema.l"
{ BEGIN(INITIAL);
					   printf("\n\n"); }
	YY_BREAK
case YY_STATE_EOF(commentSharpTask):
#line 182 "tema.l"
{ BEGIN(INITIAL); printf("\n\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 184 "tema.l"
;
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 185 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(commentSharp):
#line 186 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 188 "tema.l"
{ BEGIN(INITIAL); printf("\n\n"); }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 190 "tema.l"
;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 191 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 193 "tema.l"
{ functions->nrParamsAccept++; /* new accepts parameter read*/ }
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 194 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 195 "tema.l"
;
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 197 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 198 "tema.l"
;
	YY_BREAK
case 20:
/* rule 20 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 200 "tema.l"
{  // time to read parameters for the outer function
							BEGIN(mainFunctionParams);
							functions->nrParams = 1;
							functions->params = (TParam*) malloc(sizeof(TParam));
						 	functions->params->name = (char*) calloc(MAX_BUFF, sizeof(char));
						 	functions->params->hasDefaultValue = 0;
						 	functions->params->defaultValue = NULL;
						 	functions->nrCodeLines = 0;
						 	functions->nrReturns = 0;
						 	functions->nrTODOs = 0; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 210 "tema.l"
{ // there are no parameters
					BEGIN(mainFunctionParams);
					functions->nrParams = 0;
					functions->nrCodeLines = 0;
					functions->nrReturns = 0;
					functions->nrTODOs = 0; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 216 "tema.l"
;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 217 "tema.l"
{ // obtain outer function's name
				  functions->name[functions->size_of_name] = yytext[0];
				  functions->size_of_name++; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 221 "tema.l"
{ // obtain default value for parameters that have default values
						  BEGIN(mainFunctionParamsDefaultValues);
						  if (functions->nrParams == 1)
						  {
						   		functions->params->hasDefaultValue = 1;
						   		functions->params->defaultValue = (char*) calloc(MAX_BUFF, sizeof(char));
						  }
						  else
						  {
								functions->params[functions->nrParams - 1].defaultValue = (char*) calloc(MAX_BUFF, sizeof(char));
						  		functions->params[functions->nrParams - 1].hasDefaultValue = 1;
						  }; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 233 "tema.l"
{ // new parameter comes next
						  functions->nrParams++;
						  functions->params = (TParam*) realloc(functions->params, functions->nrParams * sizeof(TParam));
						  functions->params[functions->nrParams - 1].name = (char*) calloc(MAX_BUFF, sizeof(char));
						  functions->params[functions->nrParams - 1].hasDefaultValue = 0; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 238 "tema.l"
{ // end of parameters reading
								 BEGIN(mainFunctionLines);
								 printFunctionPart1(); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 241 "tema.l"
{ // read parameter's name
								 if (functions->nrParams == 1)
							     {
							   		strcat(functions->params->name, yytext);
							     }
							     else
							     {
								 	strcat(functions->params[functions->nrParams - 1].name, yytext);
							     }; }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 250 "tema.l"
;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 252 "tema.l"
{ // new parameter found
									   BEGIN(mainFunctionParams);
									   functions->nrParams++;
									   functions->params = (TParam*) realloc(functions->params, functions->nrParams * sizeof(TParam));
									   functions->params[functions->nrParams - 1].name = (char*) calloc(MAX_BUFF, sizeof(char));
									   functions->params[functions->nrParams - 1].hasDefaultValue = 0; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 258 "tema.l"
{ // end of reading parameters
											  BEGIN(mainFunctionLines);
											  printFunctionPart1(); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 261 "tema.l"
{ // obtain default values for certain parameters
										  if (functions->nrParams == 1)
										  {
										   		strcat(functions->params->defaultValue, yytext);
										  }
										  else
										  {
										 		strcat(functions->params[functions->nrParams - 1].defaultValue, yytext);
										  }; }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 270 "tema.l"
;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 272 "tema.l"
{ BEGIN(mainFunctionCommentSharpTODO);
												  functions->nrTODOs++; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 274 "tema.l"
{ BEGIN(mainFunctionCommentSharp); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 275 "tema.l"
{ BEGIN(mainFunctionCommentQuoteTODO);
													  functions->nrTODOs++; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 277 "tema.l"
{ BEGIN(mainFunctionCommentQuote); }
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 278 "tema.l"
{ BEGIN(mainFunctionLinesBegin);
						functions->nrCodeLines++; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 280 "tema.l"
;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 282 "tema.l"
{ BEGIN(mainFunctionReturnLines); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 283 "tema.l"
{ BEGIN(INITIAL);
							printFunctionPart2();
							freeFunction(); nr_functions = 0;
							// no indentation found so we exited function
							yyless(0); }
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 288 "tema.l"
;
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 290 "tema.l"
{ BEGIN(mainFunctionLines);
									 			  functions->nrReturns++; }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 292 "tema.l"
{ BEGIN(mainFunctionLinesBegin);
												   functions->nrCodeLines++;
												   functions->nrReturns++; }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 295 "tema.l"
{ BEGIN(mainFunctionLinesBegin); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 296 "tema.l"
{ BEGIN(mainFunctionCommentSharpTODO);
												  	    functions->nrTODOs++; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 298 "tema.l"
{ BEGIN(mainFunctionCommentSharp); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 299 "tema.l"
{ BEGIN(mainFunctionCommentQuoteTODO);
													 		functions->nrTODOs++; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 301 "tema.l"
{ BEGIN(mainFunctionCommentQuote); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 302 "tema.l"
{ // found inner functions decorator
									   BEGIN(decoratorAcceptsInner);
									   // alocate inner function
					   				   nr_functions++;
									   functions = (TFunctionPy*) realloc(functions, nr_functions * sizeof(TFunctionPy));
									   functions[nr_functions - 1].nrParamsAccept = 0;
									   functions[nr_functions - 1].nrReturns = 0;
									   functions[nr_functions - 1].nrParams = 0;
									   functions[nr_functions - 1].isDecoratorReturn = 0;
									   alreadyAllocated = 1; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 312 "tema.l"
{ // found inner functions decorator
									   BEGIN(decoratorReturnsInner);
									   // alocate inner function if it wasn't already allocated
									   if (alreadyAllocated == 1)
									   {
									   		functions[nr_functions - 1].isDecoratorReturn = 1;
									   }
									   else
									   {
											nr_functions++;
											functions = (TFunctionPy*) realloc(functions, nr_functions * sizeof(TFunctionPy));
										    functions[nr_functions - 1].nrParamsAccept = -1;
										    functions[nr_functions - 1].nrReturns = 0;
										    functions[nr_functions - 1].nrParams = 0;
										    functions[nr_functions - 1].isDecoratorReturn = 1;
										    alreadyAllocated = 1;
									   }; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 329 "tema.l"
{ // found inner function
								 BEGIN(innerFunction);
								 // allocate inner function if it wasn't already allocated
								 if (alreadyAllocated == 1)
							     {
							   		alreadyAllocated = 0;
							   	 }
							     else
							     {
									nr_functions++;
									functions = (TFunctionPy*) realloc(functions, nr_functions * sizeof(TFunctionPy));
									functions[nr_functions - 1].nrParamsAccept = -1;
									functions[nr_functions - 1].nrParams = 0;
									alreadyAllocated = 0;
							     };
							     functions[nr_functions - 1].size_of_name = 0;
							     functions[nr_functions - 1].name = (char*) calloc(MAX_BUFF, sizeof(char)); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 346 "tema.l"
{ BEGIN(mainFunctionLines); }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 348 "tema.l"
{ BEGIN(mainFunctionLinesBegin); }
	YY_BREAK
case YY_STATE_EOF(mainFunctionCommentSharpTODO):
#line 349 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 350 "tema.l"
;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 352 "tema.l"
;
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 353 "tema.l"
{ BEGIN(mainFunctionLinesBegin); }
	YY_BREAK
case YY_STATE_EOF(mainFunctionCommentSharp):
#line 354 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 356 "tema.l"
{ BEGIN(mainFunctionLinesBegin); }
	YY_BREAK
case YY_STATE_EOF(mainFunctionCommentQuoteTODO):
#line 357 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 358 "tema.l"
;
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 360 "tema.l"
;
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 361 "tema.l"
{ BEGIN(mainFunctionLinesBegin); }
	YY_BREAK
case YY_STATE_EOF(mainFunctionCommentQuote):
#line 362 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 364 "tema.l"
{ functions[nr_functions - 1].nrParamsAccept++; /* inner function's new accepts parameter */}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 365 "tema.l"
{ BEGIN(innerFunctionLinesBegin); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 366 "tema.l"
;
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 368 "tema.l"
{ BEGIN(innerFunctionLinesBegin); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 369 "tema.l"
;
	YY_BREAK
case 66:
/* rule 66 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 1);
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 371 "tema.l"
{ // inner function with parameters (allocate space for them)
							BEGIN(innerFunctionParams);
							functions[nr_functions - 1].nrParams = 1;
							functions[nr_functions - 1].params = (TParam*) malloc(sizeof(TParam));
						 	functions[nr_functions - 1].params->name = (char*) calloc(MAX_BUFF, sizeof(char));
						 	functions[nr_functions - 1].params->hasDefaultValue = 0;
						 	functions[nr_functions - 1].params->defaultValue = NULL;
						 	functions[nr_functions - 1].nrCodeLines = 0;
						 	functions[nr_functions - 1].nrReturns = 0;
						 	functions[nr_functions - 1].nrTODOs = 0; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 381 "tema.l"
{ // inner function without parameters
					 BEGIN(innerFunctionParams);
					 functions[nr_functions - 1].nrParams = 0;
					 functions[nr_functions - 1].nrCodeLines = 0;
					 functions[nr_functions - 1].nrReturns = 0;
					 functions[nr_functions - 1].nrTODOs = 0; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 387 "tema.l"
;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 388 "tema.l"
{ // read function's name
				   functions[nr_functions - 1].name[functions[nr_functions - 1].size_of_name] = yytext[0];
				   functions[nr_functions - 1].size_of_name++; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 392 "tema.l"
{ // inner function's parameter has default value
						   BEGIN(innerFunctionParamsDefaultValues);
						   if (functions[nr_functions - 1].nrParams == 1)
						   {
						   		functions[nr_functions - 1].params->hasDefaultValue = 1;
						   		functions[nr_functions - 1].params->defaultValue = (char*) calloc(MAX_BUFF, sizeof(char));
						   }
						   else
						   {
								functions[nr_functions - 1].params[functions[nr_functions - 1].nrParams - 1].defaultValue = (char*) calloc(MAX_BUFF, sizeof(char));
						  		functions[nr_functions - 1].params[functions[nr_functions - 1].nrParams - 1].hasDefaultValue = 1;
						   }; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 404 "tema.l"
{ // new parameter to come
						   functions[nr_functions - 1].nrParams++;
						   functions[nr_functions - 1].params = (TParam*) realloc(functions[nr_functions - 1].params, functions[nr_functions - 1].nrParams * sizeof(TParam));
						   functions[nr_functions - 1].params[functions[nr_functions - 1].nrParams - 1].name = (char*) calloc(MAX_BUFF, sizeof(char));
						   functions[nr_functions - 1].params[functions[nr_functions - 1].nrParams - 1].hasDefaultValue = 0; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 409 "tema.l"
{ // end of reading inner function's parameters
								  BEGIN(innerFunctionLines);
								  printFunctionPart1(); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 412 "tema.l"
{ // read parameter's name
								  if (functions[nr_functions - 1].nrParams == 1)
							      {
							   		strcat(functions[nr_functions - 1].params->name, yytext);
							      }
							      else
							      {
								 	strcat(functions[nr_functions - 1].params[functions[nr_functions - 1].nrParams - 1].name, yytext);
							      }; }
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 421 "tema.l"
;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 423 "tema.l"
{ // comes new parameter
										BEGIN(innerFunctionParams);
									    functions[nr_functions - 1].nrParams++;
									    functions[nr_functions - 1].params = (TParam*) realloc(functions[nr_functions - 1].params, functions[nr_functions - 1].nrParams * sizeof(TParam));
									    functions[nr_functions - 1].params[functions[nr_functions - 1].nrParams - 1].name = (char*) calloc(MAX_BUFF, sizeof(char));
									    functions[nr_functions - 1].params[functions[nr_functions - 1].nrParams - 1].hasDefaultValue = 0; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 429 "tema.l"
{ // all parameters have been read
											   BEGIN(innerFunctionLines);
											   printFunctionPart1(); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 432 "tema.l"
{ // reading default value for current parameter
										   if (functions[nr_functions - 1].nrParams == 1)
										   {
										   		strcat(functions[nr_functions - 1].params->defaultValue, yytext);
										   }
										   else
										   {
										 		strcat(functions[nr_functions - 1].params[functions[nr_functions - 1].nrParams - 1].defaultValue, yytext);
										   }; }
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 441 "tema.l"
;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 443 "tema.l"
{ BEGIN(innerFunctionCommentSharpTODO);
												  	    functions[nr_functions - 1].nrTODOs++; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 445 "tema.l"
{ BEGIN(innerFunctionCommentSharp); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 446 "tema.l"
{ BEGIN(innerFunctionCommentQuoteTODO);
													 		functions[nr_functions - 1].nrTODOs++; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 448 "tema.l"
{ BEGIN(innerFunctionCommentQuote); }
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 450 "tema.l"
{ BEGIN(innerFunctionLinesBegin);
						 functions[nr_functions - 1].nrCodeLines++; nr_functions_aux = nr_functions; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 452 "tema.l"
;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 454 "tema.l"
{ // we have to read a number of tabs equal cu nr_functions - 1 to remain in function
									 if (nr_functions_aux > 1)
									 {
									 	nr_functions_aux--;
									 	BEGIN(innerFunctionLinesBegin);
									 }
									 else
									 {
										BEGIN(innerFunctionReturnLines);
									 }; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 464 "tema.l"
{ // if there was not enough tabs to remain in function then it means we exit it
							 if (nr_functions == 2) // return in outer function
							 {
							 	BEGIN(mainFunctionReturnLines);
							 }
							 else
							 {
								BEGIN(innerFunctionReturnLines); // stay in an inner function
							 }
							 printFunctionPart2();
							 freeFunction();
							 functions[nr_functions - 2].nrCodeLines += functions[nr_functions - 1].nrCodeLines;
							 nr_functions--;
							 yyless(0); }
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 478 "tema.l"
;
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 480 "tema.l"
{ BEGIN(innerFunctionLines);
									 			   functions[nr_functions - 1].nrReturns++; }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 482 "tema.l"
{ BEGIN(innerFunctionLinesBegin);
									  				functions[nr_functions - 1].nrCodeLines++;
									  				functions[nr_functions - 1].nrReturns++; }
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 485 "tema.l"
{ BEGIN(innerFunctionLinesBegin); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 486 "tema.l"
{ BEGIN(innerFunctionCommentSharpTODO);
												  	    functions[nr_functions - 1].nrTODOs++; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 488 "tema.l"
{ BEGIN(innerFunctionCommentSharp); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 489 "tema.l"
{ BEGIN(innerFunctionCommentQuoteTODO);
													 		functions[nr_functions - 1].nrTODOs++; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 491 "tema.l"
{ BEGIN(innerFunctionCommentQuote); }
	YY_BREAK
case 95:
/* rule 95 can match eol */
YY_RULE_SETUP
#line 492 "tema.l"
{ // inner function's accepts decorator found
													 BEGIN(decoratorAcceptsInner);
													 // allocate space for inner function
								   				     nr_functions++;
												     functions = (TFunctionPy*) realloc(functions, nr_functions * sizeof(TFunctionPy));
												     functions[nr_functions - 1].nrParamsAccept = 0;
												     functions[nr_functions - 1].nrReturns = 0;
												     functions[nr_functions - 1].nrParams = 0;
												     functions[nr_functions - 1].isDecoratorReturn = 0;
												     alreadyAllocated = 1; }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 502 "tema.l"
{ // inner function's returns decorator found
													 BEGIN(decoratorReturnsInner);
													 // allocate space for inner function if not already allocated
												     if (alreadyAllocated == 1)
												     {
												   		functions[nr_functions - 1].isDecoratorReturn = 1;
												     }
												     else
												     {
														nr_functions++;
														functions = (TFunctionPy*) realloc(functions, nr_functions * sizeof(TFunctionPy));
													    functions[nr_functions - 1].nrParamsAccept = -1;
													    functions[nr_functions - 1].nrReturns = 0;
													    functions[nr_functions - 1].nrParams = 0;
													    functions[nr_functions - 1].isDecoratorReturn = 1;
													    alreadyAllocated = 1;
													 }; }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 519 "tema.l"
{ // inner function found
											   BEGIN(innerFunction);
											   // allocate space for inner function if not already allocated
											   if (alreadyAllocated == 1)
										       {
										   			alreadyAllocated = 0;
										   	   }
										       else
										       {
													nr_functions++;
													functions = (TFunctionPy*) realloc(functions, nr_functions * sizeof(TFunctionPy));
													functions[nr_functions - 1].nrParamsAccept = -1;
													functions[nr_functions - 1].nrParams = 0;
													alreadyAllocated = 0;
										       };
										       functions[nr_functions - 1].size_of_name = 0;
										       functions[nr_functions - 1].name = (char*) calloc(MAX_BUFF, sizeof(char)); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 536 "tema.l"
{ BEGIN(innerFunctionLines);
							  // no return on this line so we analyze a normal line
							  yyless(0); }
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 540 "tema.l"
{ BEGIN(innerFunctionLinesBegin); }
	YY_BREAK
case YY_STATE_EOF(innerFunctionCommentSharpTODO):
#line 541 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 542 "tema.l"
;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 543 "tema.l"
;
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 544 "tema.l"
{ BEGIN(innerFunctionLinesBegin); }
	YY_BREAK
case YY_STATE_EOF(innerFunctionCommentSharp):
#line 545 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 546 "tema.l"
{ BEGIN(innerFunctionLinesBegin); }
	YY_BREAK
case YY_STATE_EOF(innerFunctionCommentQuoteTODO):
#line 547 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 548 "tema.l"
;
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 549 "tema.l"
;
	YY_BREAK
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 550 "tema.l"
{ BEGIN(innerFunctionLinesBegin); }
	YY_BREAK
case YY_STATE_EOF(innerFunctionCommentQuote):
#line 551 "tema.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 552 "tema.l"
ECHO;
	YY_BREAK
#line 2009 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(commentQuoteTask):
case YY_STATE_EOF(commentQuote):
case YY_STATE_EOF(decoratorAccepts):
case YY_STATE_EOF(decoratorReturns):
case YY_STATE_EOF(mainFunction):
case YY_STATE_EOF(mainFunctionParams):
case YY_STATE_EOF(mainFunctionParamsDefaultValues):
case YY_STATE_EOF(mainFunctionLines):
case YY_STATE_EOF(mainFunctionLinesBegin):
case YY_STATE_EOF(mainFunctionReturnLines):
case YY_STATE_EOF(decoratorAcceptsInner):
case YY_STATE_EOF(decoratorReturnsInner):
case YY_STATE_EOF(innerFunction):
case YY_STATE_EOF(innerFunctionParams):
case YY_STATE_EOF(innerFunctionParamsDefaultValues):
case YY_STATE_EOF(innerFunctionLines):
case YY_STATE_EOF(innerFunctionLinesBegin):
case YY_STATE_EOF(innerFunctionReturnLines):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 345 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 345 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 344);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 552 "tema.l"



int main()
{
	yylex();
	return 0;
}
